version: "3"

services:
  paho:
    image: python-paho
    restart: on-failure:10
    volumes:
      - .:/solar:rw
    working_dir: /solar
    environment:
      - CLIENT_TEST=0
    entrypoint: ["/solar/client.py"]

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: on-failure:10
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-config:/mosquitto/config:rw
      - ./mqtt-data:/mosquitto/data:rw
      - ./mqtt-log:/mosquitto/log:rw

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/provisioning:${GF_PATHS_PROVISIONING}:rw
      - .:/solar:rw
    depends_on:
      - influxdb
    env_file:
      - .env
    ports:
      - ${GRAFANA_PORT}:3000
    entrypoint: ["/solar/grafana-entrypoint.sh"]

volumes:
  grafana-storage:
  influxdb-storage:
