apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: grafana
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    jsonData:
      version: Flux
      organization: solar
      defaultBucket: telegraf
