"Cost" = "Cost"
"Gain" = "Gain"
"RowTitleStats" = "Current Status, Consumption and Yield"
"RowTitleFeed" = "Yield to Grid"
"RowTitleGraphs" = "Trending Graphs"
"BatSOC" = "Battery SoC"
"PVPowerCurrent" = "PV Pwr Current"
"BatLoadGet" = "Bat. +Load/-Get"
"InvPower" = "Inverter Power"
"GridFeedGet" = "To Grid +Feed/-Get"
"ToHouse" = "To House"
"GridCostTotal" = "Grid Cost Total"
"DailyGain" = "Daily Yield"
"TotalGain" = "Total Gain"
"MonthlyGain" = "Monthly Gain"
"TotalYield" = "PV Yield Total"
"PVPowerTrend" = "Trend PV Power"
"DailyYieldVsGridFeed" = "Daily PV Yield and Power to Grid"
"PVYieldTotal" = "PV Yield Total"
"PVYieldLine1" = "PV Array South"
"PVYieldLine2" = "PV Array West 1"
"PVYieldLine3" = "PV Array West 2"
"PVYieldLine4" = "PV Array East"
"PVYieldPerDay" = "PV Yield per Day"
"ToGrid" = "Power to Grid"
"HourlyCostGain" = "Hourly Grid Costs / To Grid Gains"
"CostLabel" = "Cost"
"GainLabel" = "Gains"
"DailyCostGain" = "Daily Grid Costs / To Grid Gains"
"MonthlyCostGain" = "Monthly Grid Costs / To Grid Gains"
"ToGridTotal" = "To Grid Total"
"MonthlySOCStats" = "Monthly battery charce stats (relative to daily max values)"
"MedianSOC" = "Median"
"MinSOC" = "Minimum"
"MaxSOC" = "Maximum"
